### ISSUE TITLE
Error in Splitting the jid when writing to a bare JID

### ISSUE THREAD

**Issue by kalkin** [kalkin/gajim-omemo#1]
```
 gajim.c.ged Error while running an even handler: <bound method OtrPlugin.handle_outgoing_msg_stanza of <gotr.otrmodule.OtrPlugin object at 0x7fc537a31bd0>>
Traceback (most recent call last):
  File "/home/user/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/user/.local/share/gajim/plugins/gotr/otrmodule.py", line 628, in handle_outgoing_msg_stanza
    getContext(event.msg_iq.getTo()).\
  File "/home/user/.local/share/gajim/plugins/gotr/potr/context.py", line 536, in getContext
    self.ctxs[uid] = self.contextclass(self, uid)
  File "/home/user/.local/share/gajim/plugins/gotr/otrmodule.py", line 122, in __init__
    self.jid = get_jid_from_fjid(peer)
  File "/home/user/.local/share/gajim/plugins/gotr/otrmodule.py", line 113, in get_jid_from_fjid
    return gajim.get_room_and_nick_from_fjid(fjid)[0]
  File "/home/user/gajim/src/common/gajim.py", line 264, in get_room_and_nick_from_fjid
    l = jid.split('/', 1)
```

**Comment by kalkin** [comment]
After some investigation i figured that this is not an regression introduced by gajim-ommemo, the bug is int the otrmodule.
