### ISSUE TITLE
Contact cant receive or send OMEMO messages

### ISSUE THREAD

**Issue by vanitasvitae** [kalkin/gajim-omemo#103]
One of my contacts updated his OMEMO plugin from version 0.7.5 to 0.8.1 and now he cant send/receive messages to/from me. When he tries to send me a message there is no debug output, but when I send him a message he gets the following debug output:

```
11/08/16 11:58:33 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7ffbd09f9510>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gajim/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/usr/lib/python2.7/site-packages/gajim/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/reedts/.local/share/gajim/plugins/omemo/__init__.py", line 237, in message_received
    plaintext = state.decrypt_msg(msg_dict)
  File "/home/reedts/.local/share/gajim/plugins/omemo/omemo/state.py", line 215, in decrypt_msg
    result = unicode(decrypt(key, iv, payload))
  File "/home/reedts/.local/share/gajim/plugins/omemo/omemo/aes_gcm.py", line 39, in decrypt
    plaintext = aes_decrypt(key, iv, ciphertext).decode('utf-8')
  File "/home/reedts/.local/share/gajim/plugins/omemo/omemo/aes_gcm_native.py", line 43, in aes_decrypt
    _backend = default_backend()
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 35, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 21, in _available_backends
    for ep in pkg_resources.iter_entry_points(
  File "/usr/lib/python2.7/site-packages/gajim/common/demandimport.py", line 86, in __getattribute__
    self._load()
  File "/usr/lib/python2.7/site-packages/gajim/common/demandimport.py", line 58, in _load
    mod = _origimport(head, globals, locals)
ImportError: No module named pkg_resources
```

He is running Archlinux. It worked before.
We tried both installing the plugin from ftp.gajim.org and via git clone.

**Comment by vanitasvitae** [comment]
We found the error. My contact had to upgrade setuptools and distribution via

```
sudo pip2 install --upgrade setuptools
sudo pip2 install --upgrade distribution
```

**Comment by lovetox** [comment]
thanks for the report, we will add this to the dependency list for the arch package

**Comment by cippaciong** [comment]
@vanitasvitae if you prefer to avoid handling dependencies and updates manually, I made an AUR package for [gajim-omemo](https://aur.archlinux.org/packages/gajim-plugin-omemo/) some time ago. :wink:

**Comment by vanitasvitae** [comment]
@cippaciong: im using Debian :)
