### ISSUE TITLE
Gajim fails to draw QR code necessary for Conversations

### ISSUE THREAD

**Issue by TheLastProject** [kalkin/gajim-omemo#149]
i saw the warning to install python-qrcode and did so, but after that no QR code is drawn and an error report is given.

This is on Debian Testing.

```
Traceback (most recent call last):
  File "/home/sylvia/.local/share/gajim/plugins/omemo/ui.py", line 397, in account_combobox_changed_cb
    self.update_context_list()
  File "/home/sylvia/.local/share/gajim/plugins/omemo/ui.py", line 635, in update_context_list
    gajim.get_jid_from_account(account), deviceid, ownfpr[2:])
  File "/home/sylvia/.local/share/gajim/plugins/omemo/ui.py", line 414, in get_qrcode
    img.save(path)
  File "/usr/lib/python2.7/dist-packages/qrcode/image/pil.py", line 47, in save
    self._img.save(stream, format=format, **kwargs)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1695, in save
    fp = builtins.open(filename, "w+b")
  File "/usr/share/gajim/src/common/demandimport.py", line 86, in __getattribute__
    self._load()
  File "/usr/share/gajim/src/common/demandimport.py", line 58, in _load
    mod = _origimport(head, globals, locals)
ImportError: No module named builtins
```

**Comment by cippaciong** [comment]
Hi, the development of this plugin moved to https://dev.gajim.org
The same error you are reporting is being discussed [here](https://dev.gajim.org/gajim/gajim-plugins/issues/158)

**Comment by TheLastProject** [comment]
Oh, didn't think of checking the README before reporting this, thanks!
