### ISSUE TITLE
OMEMO Configuration: ImportError: No module named builtins

### ISSUE THREAD

**Issue by schiessle** [kalkin/gajim-omemo#150]
I just updated the OMEMO plugin to 1.0.0. If I go now to the settings of the Plugin I get this error message:

````
Traceback (most recent call last):
  File "/home/schiesbn/.local/share/gajim/plugins/omemo/ui.py", line 397, in account_combobox_changed_cb
    self.update_context_list()
  File "/home/schiesbn/.local/share/gajim/plugins/omemo/ui.py", line 635, in update_context_list
    gajim.get_jid_from_account(account), deviceid, ownfpr[2:])
  File "/home/schiesbn/.local/share/gajim/plugins/omemo/ui.py", line 414, in get_qrcode
    img.save(path)
  File "/usr/lib/python2.7/dist-packages/qrcode/image/pil.py", line 47, in save
    self._img.save(stream, format=format, **kwargs)
  File "/home/schiesbn/.local/lib/python2.7/site-packages/PIL/Image.py", line 1695, in save
    fp = builtins.open(filename, "w+b")
  File "/usr/share/gajim/src/common/demandimport.py", line 86, in __getattribute__
    self._load()
  File "/usr/share/gajim/src/common/demandimport.py", line 58, in _load
    mod = _origimport(head, globals, locals)
ImportError: No module named builtins
````

The settings dialog is loaded and everything seems to work, still the error looks strange.

**Comment by cippaciong** [comment]
#149

**Comment by schiessle** [comment]
yes, just found the same issue on gitlab 😄
