### ISSUE TITLE
Update to 0.7.0 failed

### ISSUE THREAD

**Issue by schiessle** [kalkin/gajim-omemo#80]
I just tried to update the OMEMO plugin to 0.7.0 this failed with following error message which left me without OMEMO support since the previous version was already removed:

```
Traceback (most recent call last):
  File "/home/schiesbn/.local/share/gajim/plugins/plugin_installer/plugin_installer.py", line 337, in on_plugin_downloaded
    plugins = self.scan_dir_for_plugin(plugin_dir)
  File "/home/schiesbn/.local/share/gajim/plugins/plugin_installer/plugin_installer.py", line 447, in scan_dir_for_plugin
    if not issubclass(module_attr, GajimPlugin) or \
  File "/usr/share/gajim/src/common/demandimport.py", line 86, in __getattribute__
    self._load()
  File "/usr/share/gajim/src/common/demandimport.py", line 58, in _load
    mod = _origimport(head, globals, locals)
ImportError: No module named NoSessionException
```

Additional information:

Gajim: 0.16.5
GTK+ Version: 2.24.30
PyGTK Version: 2.24.0
Distribution: Debian testing

**Comment by schiessle** [comment]
After restarting Gajim the plugin seems to be installed and works. Still a strange error message during update. Any ideas why this happens?

**Comment by kalkin** [comment]
@schiessle Yes, we know why it happens. Gajim needs to release new version. WIP

**Comment by kalkin** [comment]
@schiessle Neverless thank you for the report ☺

**Comment by schiessle** [comment]
@kalkin Thanks! Looking forward to the new Gajim version :smiley:
